# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 393b85e7d15dfcda8ec7b096b019e0b7927381562998da63ef3966badeae717d9095b0fea2a6048951fc7ce403268de8f12c23a402c96733f419f0bd97557682

test:
  secret_key_base: 2328e2f15b2502d22b15aca9c5855a506d3055c30fdd4d0596417a8f7c959d2ca811bc2790022d3d29897c118ef754e70ed630432183558d3b8fdc63e1ed4c2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
